use CCP;

drop TABLE if exists DIPENDENTI, PAZIENTI, TURNI_LAVORO, PIANO_TERAPEUTICO, TERAPIA, DIARIO_PARAMETRI, MONITORAGGI ;

CREATE TABLE DIPENDENTI
	(	ID smallint AUTO_INCREMENT UNIQUE ,
		ID_DIPENDENTE CHAR(10) primary key,
		CODICE_FISCALE CHAR (16) UNIQUE,
		NOME VARCHAR (14) NOT NULL ,
		COGNOME VARCHAR (16) NOT NULL,
        DATA_DI_NASCITA DATE NOT NULL,
        EMAIL VARCHAR (30),
        NUMERO_TELEFONICO VARCHAR (30),
		DIPENDENTE_PASSWORD char (8),
        RUOLO CHAR (18),
        DATA_INIZIO CHAR (12) NOT NULL
	);
    
CREATE TABLE PAZIENTI 
	(	CODICE_FISCALE CHAR (16) PRIMARY KEY,
		NOME VArCHAR (14) NOT NULL ,
        COGNOME VARCHAR (16) NOT NULL,
        DATA_DI_NASCITA DATE,
        EMAIL VARCHAR (30),
        NUM_TEL_PARENTE CHAR (30)
    );
    
     CREATE TABLE TURNI_LAVORO 
     (	ID_TURNO INT PRIMARY KEY,
		ID_DIPENDENTE CHAR(10),
		DATA_TURNO DATE,
		ORA_INIZIO TIME,
		ORA_FINE TIME,
		FOREIGN KEY (ID_DIPENDENTE) REFERENCES DIPENDENTI(ID_DIPENDENTE)
	);

    CREATE TABLE PIANO_TERAPEUTICO (
		ID smallint AUTO_INCREMENT UNIQUE ,
		ID_PIANO_TER CHAR(10) PRIMARY KEY,
		ID_PAZIENTE CHAR(16) NOT NULL,
		DATA_CREAZIONE DATE NOT NULL,
		FOREIGN KEY (ID_PAZIENTE) REFERENCES PAZIENTI(CODICE_FISCALE)
	);

	CREATE TABLE TERAPIA (
		ID smallint AUTO_INCREMENT UNIQUE ,
		ID_TERAPIA CHAR(10) PRIMARY KEY,
		ID_PIANO_TER CHAR(10) NOT NULL,
		ID_MEDICO CHAR(10) NOT NULL,
		TIPO_SOMMINISTRAZIONE VARCHAR(50) NOT NULL,
		NOME_FARMACO VARCHAR(100),
		MATERIALE_UTILIZZATO VARCHAR(100),
		DOSAGGIO VARCHAR(50),
		FREQUENZA_GIORNALIERA SMALLINT NOT NULL,
		STATO VARCHAR(20) NOT NULL,
		DURATA SMALLINT NOT NULL,
		DATA_INIZIO DATE NOT NULL,
		DATA_FINE DATE NOT NULL,
		NOTE VARCHAR(255),
		FOREIGN KEY (ID_MEDICO) REFERENCES DIPENDENTI(ID_DIPENDENTE),
		FOREIGN KEY (ID_PIANO_TER) REFERENCES PIANO_TERAPEUTICO(ID_PIANO_TER)
);

CREATE TABLE DIARIO_PARAMETRI 
	( 	ID smallint AUTO_INCREMENT UNIQUE ,
		ID_DIARIO VARchar(10)  PRIMARY KEY,
        ID_PAZIENTE CHAR (16),
        FOREIGN KEY (ID_PAZIENTE) REFERENCES PAZIENTI(CODICE_FISCALE)
    );
    
CREATE TABLE MONITORAGGI (
		ID smallint AUTO_INCREMENT UNIQUE ,
        ID_RILEVAZIONE SMALLINT,
        ID_DIARIO SMALLINT,
		ID_DIPENDENTE CHAR(10),
        ID_PAZIENTE CHAR (16),
		TIPO_PARAMETRO CHAR (50) NOT NULL, 
        DATA_MONITORAGGIO DATE NOT NULL,
        STATO CHAR (15) NOT NULL, 
        VALORE CHAR (10),
        FOREIGN KEY (ID_PAZIENTE) REFERENCES PAZIENTI(CODICE_FISCALE),
        foreign key (ID_DIPENDENTE) references DIPENDENTI(ID_DIPENDENTE)
        
);